import streamlit as sl

commital = sl.slider('How committed are you to emit less Carbon Emissions?', 0, 100)
q2 = sl.slider('How many kilometres do you drive on average a week', 0, 5000)
q3 = input()
q4 = input()
q5 = input()
q6 = input()
q7 = input()
q8 = input()
q9 = input()
q10 = input()
q11 = input()
q12 = input()
q13 = input()
q14 = input()
q15 = input()
q16 = input()
q17 = input()
q18 = input()
q19 = input()
q20 = input()
q21 = input()
q22 = input()
commital = input()
